### ISSUE TITLE
Flaky mirror node deploys

### ISSUE THREAD

**Issue by gsstoykov** [hiero-ledger/hiero-solo-action#53]
### Description

``` 
******************************* Solo *********************************************
Version			: 0.35.2
Kubernetes Context	: kind-solo-e2e
Kubernetes Cluster	: kind-solo-e2e
Current Command		: mirror-node deploy --deployment solo-deployment
**********************************************************************************
❯ Initialize
❯ Acquire lease
✔ Acquire lease - lease acquired successfully, attempt: 1/10
✔ Initialize
❯ Enable mirror-node
❯ Prepare address book
✔ Prepare address book
❯ Deploy mirror-node
✔ Deploy mirror-node
✔ Enable mirror-node
❯ Check pods are ready
❯ Check Postgres DB
❯ Check REST API
❯ Check GRPC
❯ Check Monitor
❯ Check Importer
✔ Check Postgres DB
✔ Check GRPC
✔ Check Monitor
✔ Check Importer
✖ Check REST API [FAILED: Pod not ready [maxAttempts = 300]]
✖ Check pods are ready [FAILED: Pod not ready [maxAttempts = 300]]
*********************************** ERROR *****************************************
Error deploying node: Pod not ready [maxAttempts = 300]
***********************************************************************************
``` 
Has been seen in multiple scenarios after attempting solo-action start. Not working for all versions different than the default `v0.58.10`.

### Steps to reproduce

```
- name: Prepare Hiero Solo
        id: solo
        uses: hiero-ledger/hiero-solo-action@d5e345ca83d7c2b73d9d4f090276d70babe1dc73 # v0.7
        with:
          hieroVersion: "v0.61.3"
          installMirrorNode: true
```

### Version

latest

### Operating system

None
